default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: root
  password: tiger
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: 5433

development:
  <<: *default
  database: llm_chat_app_development

test:
  <<: *default
  database: llm_chat_app_test

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
